### ISSUE TITLE
In the editor can work normally, but there is a dot card. But on Hololens, there's no video, it's white.

### ISSUE THREAD

**Issue by shoukailiang** [cookieofcode/LabAssistVision#14]
**Describe the bug**
In the editor can work normally. But on Hololens, there's no video, it's white.

unity2019.4.34f opencv for unity 2.4.1

**Comment by Birkenpapier** [comment]
Did you solved it?

**Comment by shoukailiang** [comment]
> Did you solved it?

I didn't solve the problem in the end.

**Comment by Birkenpapier** [comment]
Sad, but thank you for the answer.

**Comment by cookieofcode** [comment]
Hi @shoukailiang. Unfortunately, I don't have access to a HoloLens 2 anymore. Make sure that you applied the Project Configurations listed in https://github.com/cookieofcode/LabAssistVision#project-configuration. Otherwise please ensure that you use Unity Version 2019.4.15f1 and dependency versions specified in https://github.com/cookieofcode/LabAssistVision#dependencies.
